<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLike($search) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a
            FROM AppBundle:Article a
            WHERE a.name LIKE :search')
            ->setParameter('search',$search.'%')
            ->getResult();
    }
}
