<?php

namespace AppBundle\Repository;

/**
 * CartElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartElementRepository extends \Doctrine\ORM\EntityRepository
{
}
