<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLike($search) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c
            FROM AppBundle:Category c
            WHERE c.name LIKE :search')
            ->setParameter('search',$search.'%')
            ->getResult();
    }
}
