<?php

namespace AppBundle\Repository;

/**
 * CharacteristicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicsRepository extends \Doctrine\ORM\EntityRepository
{
}
