<?php

namespace AppBundle\Repository;

/**
 * FavsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavsRepository extends \Doctrine\ORM\EntityRepository
{
}
