<?php

namespace AppBundle\Repository;

/**
 * UserCommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCommandRepository extends \Doctrine\ORM\EntityRepository
{
}
